### ISSUE TITLE
No translation of title and alt

### ISSUE THREAD

**Issue by kujiu** [sphinx-contrib/images#13] opened 2020-06-04 14:40 UTC
Translation of text in image attributes miss.

# How to reproduce

Create a project with sphinx-quickstart, add an image on index.rst and set a :title: and an :alt:.

Then, launch compilation with "make gettext". The content of :title: and of :alt: are not in the index.pot file.

**Comment by jonascj** [comment] 2020-06-08 20:28
Does it work as intended without sphinxcontrib-images loaded? I assume it does, if you add your image to index.rst as below:

```
.. image:: fig.png
   :alt: my alternate text
   :title: my title
```

**Comment by kujiu** [comment] 2020-06-08 20:35
No, it doesn't. I opened the same issue here : https://github.com/sphinx-doc/sphinx/issues/7784

**Comment by jonascj** [comment] 2020-06-08 20:41
Then I'll close it as an upstream issue. Feel free to open a new issue if it gets fixed upstream but appears again when using sphinxcontrib-images.

**Closed by jonascj** 2020-06-08 20:41 UTC
